package com.wzp.aiplatform.mapper;

import com.wzp.aiplatform.model.Label;
import com.wzp.aiplatform.model.LabelExample;
import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.DeleteProvider;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.InsertProvider;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.SelectProvider;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.annotations.UpdateProvider;
import org.apache.ibatis.type.JdbcType;
import org.springframework.stereotype.Repository;

@Repository
public interface LabelMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table label
     *
     * @mbg.generated Sat Apr 13 12:01:15 CST 2019
     */
    @SelectProvider(type=LabelSqlProvider.class, method="countByExample")
    long countByExample(LabelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table label
     *
     * @mbg.generated Sat Apr 13 12:01:15 CST 2019
     */
    @DeleteProvider(type=LabelSqlProvider.class, method="deleteByExample")
    int deleteByExample(LabelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table label
     *
     * @mbg.generated Sat Apr 13 12:01:15 CST 2019
     */
    @Delete({
        "delete from label",
        "where labelid = #{labelid,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(Integer labelid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table label
     *
     * @mbg.generated Sat Apr 13 12:01:15 CST 2019
     */
    @Insert({
        "insert into label (labelid, tasklistid, ",
        "content, taskid)",
        "values (#{labelid,jdbcType=INTEGER}, #{tasklistid,jdbcType=INTEGER}, ",
        "#{content,jdbcType=VARCHAR}, #{taskid,jdbcType=INTEGER})"
    })
    int insert(Label record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table label
     *
     * @mbg.generated Sat Apr 13 12:01:15 CST 2019
     */
    @InsertProvider(type=LabelSqlProvider.class, method="insertSelective")
    int insertSelective(Label record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table label
     *
     * @mbg.generated Sat Apr 13 12:01:15 CST 2019
     */
    @SelectProvider(type=LabelSqlProvider.class, method="selectByExample")
    @Results({
        @Result(column="labelid", property="labelid", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="tasklistid", property="tasklistid", jdbcType=JdbcType.INTEGER),
        @Result(column="content", property="content", jdbcType=JdbcType.VARCHAR),
        @Result(column="taskid", property="taskid", jdbcType=JdbcType.INTEGER)
    })
    List<Label> selectByExample(LabelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table label
     *
     * @mbg.generated Sat Apr 13 12:01:15 CST 2019
     */
    @Select({
        "select",
        "labelid, tasklistid, content, taskid",
        "from label",
        "where labelid = #{labelid,jdbcType=INTEGER}"
    })
    @Results({
        @Result(column="labelid", property="labelid", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="tasklistid", property="tasklistid", jdbcType=JdbcType.INTEGER),
        @Result(column="content", property="content", jdbcType=JdbcType.VARCHAR),
        @Result(column="taskid", property="taskid", jdbcType=JdbcType.INTEGER)
    })
    Label selectByPrimaryKey(Integer labelid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table label
     *
     * @mbg.generated Sat Apr 13 12:01:15 CST 2019
     */
    @UpdateProvider(type=LabelSqlProvider.class, method="updateByExampleSelective")
    int updateByExampleSelective(@Param("record") Label record, @Param("example") LabelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table label
     *
     * @mbg.generated Sat Apr 13 12:01:15 CST 2019
     */
    @UpdateProvider(type=LabelSqlProvider.class, method="updateByExample")
    int updateByExample(@Param("record") Label record, @Param("example") LabelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table label
     *
     * @mbg.generated Sat Apr 13 12:01:15 CST 2019
     */
    @UpdateProvider(type=LabelSqlProvider.class, method="updateByPrimaryKeySelective")
    int updateByPrimaryKeySelective(Label record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table label
     *
     * @mbg.generated Sat Apr 13 12:01:15 CST 2019
     */
    @Update({
        "update label",
        "set tasklistid = #{tasklistid,jdbcType=INTEGER},",
          "content = #{content,jdbcType=VARCHAR},",
          "taskid = #{taskid,jdbcType=INTEGER}",
        "where labelid = #{labelid,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(Label record);
}