package com.wzp.aiplatform.mapper;

import com.wzp.aiplatform.model.TaskSize;
import com.wzp.aiplatform.model.TaskSizeExample;
import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.DeleteProvider;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.InsertProvider;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.SelectProvider;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.annotations.UpdateProvider;
import org.apache.ibatis.type.JdbcType;
import org.springframework.stereotype.Repository;

@Repository
public interface TaskSizeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tasksize
     *
     * @mbg.generated Tue Apr 23 16:11:40 CST 2019
     */
    @SelectProvider(type=TaskSizeSqlProvider.class, method="countByExample")
    long countByExample(TaskSizeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tasksize
     *
     * @mbg.generated Tue Apr 23 16:11:40 CST 2019
     */
    @DeleteProvider(type=TaskSizeSqlProvider.class, method="deleteByExample")
    int deleteByExample(TaskSizeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tasksize
     *
     * @mbg.generated Tue Apr 23 16:11:40 CST 2019
     */
    @Delete({
        "delete from tasksize",
        "where taskid = #{taskid,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(Integer taskid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tasksize
     *
     * @mbg.generated Tue Apr 23 16:11:40 CST 2019
     */
    @Insert({
        "insert into tasksize (taskid, tasklength)",
        "values (#{taskid,jdbcType=INTEGER}, #{tasklength,jdbcType=INTEGER})"
    })
    void insert(TaskSize record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tasksize
     *
     * @mbg.generated Tue Apr 23 16:11:40 CST 2019
     */
    @InsertProvider(type=TaskSizeSqlProvider.class, method="insertSelective")
    int insertSelective(TaskSize record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tasksize
     *
     * @mbg.generated Tue Apr 23 16:11:40 CST 2019
     */
    @SelectProvider(type=TaskSizeSqlProvider.class, method="selectByExample")
    @Results({
        @Result(column="taskid", property="taskid", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="tasklength", property="tasklength", jdbcType=JdbcType.INTEGER)
    })
    List<TaskSize> selectByExample(TaskSizeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tasksize
     *
     * @mbg.generated Tue Apr 23 16:11:40 CST 2019
     */
    @Select({
        "select",
        "taskid, tasklength",
        "from tasksize",
        "where taskid = #{taskid,jdbcType=INTEGER}"
    })
    @Results({
        @Result(column="taskid", property="taskid", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="tasklength", property="tasklength", jdbcType=JdbcType.INTEGER)
    })
    TaskSize selectByPrimaryKey(Integer taskid);

    @Select({
            "select",
            "tasklength",
            "from tasksize",
            "where taskid = #{taskid,jdbcType=INTEGER}"
    })
    @Results({
            @Result(column="tasklength", property="tasklength", jdbcType=JdbcType.INTEGER)
    })
    Integer selectLength(Integer taskid);
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tasksize
     *
     * @mbg.generated Tue Apr 23 16:11:40 CST 2019
     */
    @UpdateProvider(type=TaskSizeSqlProvider.class, method="updateByExampleSelective")
    int updateByExampleSelective(@Param("record") TaskSize record, @Param("example") TaskSizeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tasksize
     *
     * @mbg.generated Tue Apr 23 16:11:40 CST 2019
     */
    @UpdateProvider(type=TaskSizeSqlProvider.class, method="updateByExample")
    int updateByExample(@Param("record") TaskSize record, @Param("example") TaskSizeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tasksize
     *
     * @mbg.generated Tue Apr 23 16:11:40 CST 2019
     */
    @UpdateProvider(type=TaskSizeSqlProvider.class, method="updateByPrimaryKeySelective")
    int updateByPrimaryKeySelective(TaskSize record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tasksize
     *
     * @mbg.generated Tue Apr 23 16:11:40 CST 2019
     */
    @Update({
        "update tasksize",
        "set tasklength = #{tasklength,jdbcType=INTEGER}",
        "where taskid = #{taskid,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(TaskSize record);
}