package com.wzp.aiplatform.mapper;

import com.wzp.aiplatform.model.TaskSize;
import com.wzp.aiplatform.model.TaskSizeExample.Criteria;
import com.wzp.aiplatform.model.TaskSizeExample.Criterion;
import com.wzp.aiplatform.model.TaskSizeExample;
import java.util.List;
import java.util.Map;
import org.apache.ibatis.jdbc.SQL;

public class TaskSizeSqlProvider {

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tasksize
     *
     * @mbg.generated Tue Apr 23 16:11:40 CST 2019
     */
    public String countByExample(TaskSizeExample example) {
        SQL sql = new SQL();
        sql.SELECT("count(*)").FROM("tasksize");
        applyWhere(sql, example, false);
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tasksize
     *
     * @mbg.generated Tue Apr 23 16:11:40 CST 2019
     */
    public String deleteByExample(TaskSizeExample example) {
        SQL sql = new SQL();
        sql.DELETE_FROM("tasksize");
        applyWhere(sql, example, false);
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tasksize
     *
     * @mbg.generated Tue Apr 23 16:11:40 CST 2019
     */
    public String insertSelective(TaskSize record) {
        SQL sql = new SQL();
        sql.INSERT_INTO("tasksize");
        
        if (record.getTaskid() != null) {
            sql.VALUES("taskid", "#{taskid,jdbcType=INTEGER}");
        }
        
        if (record.getTasklength() != null) {
            sql.VALUES("tasklength", "#{tasklength,jdbcType=INTEGER}");
        }
        
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tasksize
     *
     * @mbg.generated Tue Apr 23 16:11:40 CST 2019
     */
    public String selectByExample(TaskSizeExample example) {
        SQL sql = new SQL();
        if (example != null && example.isDistinct()) {
            sql.SELECT_DISTINCT("taskid");
        } else {
            sql.SELECT("taskid");
        }
        sql.SELECT("tasklength");
        sql.FROM("tasksize");
        applyWhere(sql, example, false);
        
        if (example != null && example.getOrderByClause() != null) {
            sql.ORDER_BY(example.getOrderByClause());
        }
        
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tasksize
     *
     * @mbg.generated Tue Apr 23 16:11:40 CST 2019
     */
    public String updateByExampleSelective(Map<String, Object> parameter) {
        TaskSize record = (TaskSize) parameter.get("record");
        TaskSizeExample example = (TaskSizeExample) parameter.get("example");
        
        SQL sql = new SQL();
        sql.UPDATE("tasksize");
        
        if (record.getTaskid() != null) {
            sql.SET("taskid = #{record.taskid,jdbcType=INTEGER}");
        }
        
        if (record.getTasklength() != null) {
            sql.SET("tasklength = #{record.tasklength,jdbcType=INTEGER}");
        }
        
        applyWhere(sql, example, true);
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tasksize
     *
     * @mbg.generated Tue Apr 23 16:11:40 CST 2019
     */
    public String updateByExample(Map<String, Object> parameter) {
        SQL sql = new SQL();
        sql.UPDATE("tasksize");
        
        sql.SET("taskid = #{record.taskid,jdbcType=INTEGER}");
        sql.SET("tasklength = #{record.tasklength,jdbcType=INTEGER}");
        
        TaskSizeExample example = (TaskSizeExample) parameter.get("example");
        applyWhere(sql, example, true);
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tasksize
     *
     * @mbg.generated Tue Apr 23 16:11:40 CST 2019
     */
    public String updateByPrimaryKeySelective(TaskSize record) {
        SQL sql = new SQL();
        sql.UPDATE("tasksize");
        
        if (record.getTasklength() != null) {
            sql.SET("tasklength = #{tasklength,jdbcType=INTEGER}");
        }
        
        sql.WHERE("taskid = #{taskid,jdbcType=INTEGER}");
        
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tasksize
     *
     * @mbg.generated Tue Apr 23 16:11:40 CST 2019
     */
    protected void applyWhere(SQL sql, TaskSizeExample example, boolean includeExamplePhrase) {
        if (example == null) {
            return;
        }
        
        String parmPhrase1;
        String parmPhrase1_th;
        String parmPhrase2;
        String parmPhrase2_th;
        String parmPhrase3;
        String parmPhrase3_th;
        if (includeExamplePhrase) {
            parmPhrase1 = "%s #{example.oredCriteria[%d].allCriteria[%d].value}";
            parmPhrase1_th = "%s #{example.oredCriteria[%d].allCriteria[%d].value,typeHandler=%s}";
            parmPhrase2 = "%s #{example.oredCriteria[%d].allCriteria[%d].value} and #{example.oredCriteria[%d].criteria[%d].secondValue}";
            parmPhrase2_th = "%s #{example.oredCriteria[%d].allCriteria[%d].value,typeHandler=%s} and #{example.oredCriteria[%d].criteria[%d].secondValue,typeHandler=%s}";
            parmPhrase3 = "#{example.oredCriteria[%d].allCriteria[%d].value[%d]}";
            parmPhrase3_th = "#{example.oredCriteria[%d].allCriteria[%d].value[%d],typeHandler=%s}";
        } else {
            parmPhrase1 = "%s #{oredCriteria[%d].allCriteria[%d].value}";
            parmPhrase1_th = "%s #{oredCriteria[%d].allCriteria[%d].value,typeHandler=%s}";
            parmPhrase2 = "%s #{oredCriteria[%d].allCriteria[%d].value} and #{oredCriteria[%d].criteria[%d].secondValue}";
            parmPhrase2_th = "%s #{oredCriteria[%d].allCriteria[%d].value,typeHandler=%s} and #{oredCriteria[%d].criteria[%d].secondValue,typeHandler=%s}";
            parmPhrase3 = "#{oredCriteria[%d].allCriteria[%d].value[%d]}";
            parmPhrase3_th = "#{oredCriteria[%d].allCriteria[%d].value[%d],typeHandler=%s}";
        }
        
        StringBuilder sb = new StringBuilder();
        List<Criteria> oredCriteria = example.getOredCriteria();
        boolean firstCriteria = true;
        for (int i = 0; i < oredCriteria.size(); i++) {
            Criteria criteria = oredCriteria.get(i);
            if (criteria.isValid()) {
                if (firstCriteria) {
                    firstCriteria = false;
                } else {
                    sb.append(" or ");
                }
                
                sb.append('(');
                List<Criterion> criterions = criteria.getAllCriteria();
                boolean firstCriterion = true;
                for (int j = 0; j < criterions.size(); j++) {
                    Criterion criterion = criterions.get(j);
                    if (firstCriterion) {
                        firstCriterion = false;
                    } else {
                        sb.append(" and ");
                    }
                    
                    if (criterion.isNoValue()) {
                        sb.append(criterion.getCondition());
                    } else if (criterion.isSingleValue()) {
                        if (criterion.getTypeHandler() == null) {
                            sb.append(String.format(parmPhrase1, criterion.getCondition(), i, j));
                        } else {
                            sb.append(String.format(parmPhrase1_th, criterion.getCondition(), i, j,criterion.getTypeHandler()));
                        }
                    } else if (criterion.isBetweenValue()) {
                        if (criterion.getTypeHandler() == null) {
                            sb.append(String.format(parmPhrase2, criterion.getCondition(), i, j, i, j));
                        } else {
                            sb.append(String.format(parmPhrase2_th, criterion.getCondition(), i, j, criterion.getTypeHandler(), i, j, criterion.getTypeHandler()));
                        }
                    } else if (criterion.isListValue()) {
                        sb.append(criterion.getCondition());
                        sb.append(" (");
                        List<?> listItems = (List<?>) criterion.getValue();
                        boolean comma = false;
                        for (int k = 0; k < listItems.size(); k++) {
                            if (comma) {
                                sb.append(", ");
                            } else {
                                comma = true;
                            }
                            if (criterion.getTypeHandler() == null) {
                                sb.append(String.format(parmPhrase3, i, j, k));
                            } else {
                                sb.append(String.format(parmPhrase3_th, i, j, k, criterion.getTypeHandler()));
                            }
                        }
                        sb.append(')');
                    }
                }
                sb.append(')');
            }
        }
        
        if (sb.length() > 0) {
            sql.WHERE(sb.toString());
        }
    }
}