package com.wzp.aiplatform.mapper;

import com.wzp.aiplatform.model.TaskList;
import com.wzp.aiplatform.model.TaskListExample;
import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.DeleteProvider;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.InsertProvider;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.SelectProvider;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.annotations.UpdateProvider;
import org.apache.ibatis.type.JdbcType;
import org.springframework.stereotype.Repository;

@Repository
public interface TaskListMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tasklist
     *
     * @mbg.generated Fri Apr 12 16:23:00 CST 2019
     */
    @SelectProvider(type=TaskListSqlProvider.class, method="countByExample")
    long countByExample(TaskListExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tasklist
     *
     * @mbg.generated Fri Apr 12 16:23:00 CST 2019
     */
    @DeleteProvider(type=TaskListSqlProvider.class, method="deleteByExample")
    int deleteByExample(TaskListExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tasklist
     *
     * @mbg.generated Fri Apr 12 16:23:00 CST 2019
     */
    @Delete({
        "delete from tasklist",
        "where tasklistid = #{tasklistid,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(Integer tasklistid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tasklist
     *
     * @mbg.generated Fri Apr 12 16:23:00 CST 2019
     */
    @Insert({
        "insert into tasklist (taskid, ",
        "tasklistname)",
        "values (#{taskid,jdbcType=INTEGER}, ",
        "#{tasklistname,jdbcType=VARCHAR})"
    })
    int insert(TaskList record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tasklist
     *
     * @mbg.generated Fri Apr 12 16:23:00 CST 2019
     */
    @InsertProvider(type=TaskListSqlProvider.class, method="insertSelective")
    int insertSelective(TaskList record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tasklist
     *
     * @mbg.generated Fri Apr 12 16:23:00 CST 2019
     */
    @SelectProvider(type=TaskListSqlProvider.class, method="selectByExample")
    @Results({
        @Result(column="tasklistid", property="tasklistid", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="taskid", property="taskid", jdbcType=JdbcType.INTEGER),
        @Result(column="tasklistname", property="tasklistname", jdbcType=JdbcType.VARCHAR)
    })
    List<TaskList> selectByExample(TaskListExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tasklist
     *
     * @mbg.generated Fri Apr 12 16:23:00 CST 2019
     */
    @Select({
        "select",
        "tasklistid, taskid, tasklistname",
        "from tasklist",
        "where tasklistid = #{tasklistid,jdbcType=INTEGER}"
    })
    @Results({
        @Result(column="tasklistid", property="tasklistid", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="taskid", property="taskid", jdbcType=JdbcType.INTEGER),
        @Result(column="tasklistname", property="tasklistname", jdbcType=JdbcType.VARCHAR)
    })
    TaskList selectByPrimaryKey(Integer tasklistid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tasklist
     *
     * @mbg.generated Fri Apr 12 16:23:00 CST 2019
     */
    @UpdateProvider(type=TaskListSqlProvider.class, method="updateByExampleSelective")
    int updateByExampleSelective(@Param("record") TaskList record, @Param("example") TaskListExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tasklist
     *
     * @mbg.generated Fri Apr 12 16:23:00 CST 2019
     */
    @UpdateProvider(type=TaskListSqlProvider.class, method="updateByExample")
    int updateByExample(@Param("record") TaskList record, @Param("example") TaskListExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tasklist
     *
     * @mbg.generated Fri Apr 12 16:23:00 CST 2019
     */
    @UpdateProvider(type=TaskListSqlProvider.class, method="updateByPrimaryKeySelective")
    int updateByPrimaryKeySelective(TaskList record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tasklist
     *
     * @mbg.generated Fri Apr 12 16:23:00 CST 2019
     */
    @Update({
        "update tasklist",
        "set taskid = #{taskid,jdbcType=INTEGER},",
          "tasklistname = #{tasklistname,jdbcType=VARCHAR}",
        "where tasklistid = #{tasklistid,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(TaskList record);
}