package com.wzp.aiplatform.mapper;

import com.wzp.aiplatform.model.taskSize;
import com.wzp.aiplatform.model.taskSizeExample;
import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.DeleteProvider;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.InsertProvider;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.SelectProvider;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.annotations.UpdateProvider;
import org.apache.ibatis.type.JdbcType;
import org.springframework.stereotype.Repository;

@Repository
public interface taskSizeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tasksize
     *
     * @mbg.generated Mon Apr 22 22:28:04 CST 2019
     */
    @SelectProvider(type=taskSizeSqlProvider.class, method="countByExample")
    long countByExample(taskSizeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tasksize
     *
     * @mbg.generated Mon Apr 22 22:28:04 CST 2019
     */
    @DeleteProvider(type=taskSizeSqlProvider.class, method="deleteByExample")
    int deleteByExample(taskSizeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tasksize
     *
     * @mbg.generated Mon Apr 22 22:28:04 CST 2019
     */
    @Delete({
        "delete from tasksize",
        "where taskid = #{taskid,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(Integer taskid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tasksize
     *
     * @mbg.generated Mon Apr 22 22:28:04 CST 2019
     */
    @Insert({
        "insert into tasksize (taskid, tasklength)",
        "values (#{taskid,jdbcType=INTEGER}, #{tasklength,jdbcType=INTEGER})"
    })
    int insert(taskSize record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tasksize
     *
     * @mbg.generated Mon Apr 22 22:28:04 CST 2019
     */
    @InsertProvider(type=taskSizeSqlProvider.class, method="insertSelective")
    int insertSelective(taskSize record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tasksize
     *
     * @mbg.generated Mon Apr 22 22:28:04 CST 2019
     */
    @SelectProvider(type=taskSizeSqlProvider.class, method="selectByExample")
    @Results({
        @Result(column="taskid", property="taskid", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="tasklength", property="tasklength", jdbcType=JdbcType.INTEGER)
    })
    List<taskSize> selectByExample(taskSizeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tasksize
     *
     * @mbg.generated Mon Apr 22 22:28:04 CST 2019
     */
    @Select({
        "select",
        "taskid, tasklength",
        "from tasksize",
        "where taskid = #{taskid,jdbcType=INTEGER}"
    })
    @Results({
        @Result(column="taskid", property="taskid", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="tasklength", property="tasklength", jdbcType=JdbcType.INTEGER)
    })
    taskSize selectByPrimaryKey(Integer taskid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tasksize
     *
     * @mbg.generated Mon Apr 22 22:28:04 CST 2019
     */
    @UpdateProvider(type=taskSizeSqlProvider.class, method="updateByExampleSelective")
    int updateByExampleSelective(@Param("record") taskSize record, @Param("example") taskSizeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tasksize
     *
     * @mbg.generated Mon Apr 22 22:28:04 CST 2019
     */
    @UpdateProvider(type=taskSizeSqlProvider.class, method="updateByExample")
    int updateByExample(@Param("record") taskSize record, @Param("example") taskSizeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tasksize
     *
     * @mbg.generated Mon Apr 22 22:28:04 CST 2019
     */
    @UpdateProvider(type=taskSizeSqlProvider.class, method="updateByPrimaryKeySelective")
    int updateByPrimaryKeySelective(taskSize record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tasksize
     *
     * @mbg.generated Mon Apr 22 22:28:04 CST 2019
     */
    @Update({
        "update tasksize",
        "set tasklength = #{tasklength,jdbcType=INTEGER}",
        "where taskid = #{taskid,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(taskSize record);
}