package com.wzp.aiplatform.mapper;

import com.wzp.aiplatform.model.Zip;
import com.wzp.aiplatform.model.ZipExample;
import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.DeleteProvider;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.InsertProvider;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.SelectProvider;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.annotations.UpdateProvider;
import org.apache.ibatis.type.JdbcType;
import org.springframework.stereotype.Repository;

@Repository
public interface ZipMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zip
     *
     * @mbg.generated Sat Apr 13 12:01:15 CST 2019
     */
    @SelectProvider(type=ZipSqlProvider.class, method="countByExample")
    long countByExample(ZipExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zip
     *
     * @mbg.generated Sat Apr 13 12:01:15 CST 2019
     */
    @DeleteProvider(type=ZipSqlProvider.class, method="deleteByExample")
    int deleteByExample(ZipExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zip
     *
     * @mbg.generated Sat Apr 13 12:01:15 CST 2019
     */
    @Delete({
        "delete from zip",
        "where filename = #{filename,jdbcType=VARCHAR}"
    })
    int deleteByPrimaryKey(String filename);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zip
     *
     * @mbg.generated Sat Apr 13 12:01:15 CST 2019
     */
    @Insert({
        "insert into zip (filename, taskid)",
        "values (#{filename,jdbcType=VARCHAR}, #{taskid,jdbcType=INTEGER})"
    })
    int insert(Zip record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zip
     *
     * @mbg.generated Sat Apr 13 12:01:15 CST 2019
     */
    @InsertProvider(type=ZipSqlProvider.class, method="insertSelective")
    int insertSelective(Zip record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zip
     *
     * @mbg.generated Sat Apr 13 12:01:15 CST 2019
     */
    @SelectProvider(type=ZipSqlProvider.class, method="selectByExample")
    @Results({
        @Result(column="filename", property="filename", jdbcType=JdbcType.VARCHAR, id=true),
        @Result(column="taskid", property="taskid", jdbcType=JdbcType.INTEGER)
    })
    List<Zip> selectByExample(ZipExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zip
     *
     * @mbg.generated Sat Apr 13 12:01:15 CST 2019
     */
    @Select({
        "select",
        "filename, taskid",
        "from zip",
        "where filename = #{filename,jdbcType=VARCHAR}"
    })
    @Results({
        @Result(column="filename", property="filename", jdbcType=JdbcType.VARCHAR, id=true),
        @Result(column="taskid", property="taskid", jdbcType=JdbcType.INTEGER)
    })
    Zip selectByPrimaryKey(String filename);

    @Select({
            "select",
            "filename, taskid",
            "from zip",
            "where filename = #{filename,jdbcType=VARCHAR}"
    })
    @Results({
            @Result(column="filename", property="filename", jdbcType=JdbcType.VARCHAR, id=true),
            @Result(column="taskid", property="taskid", jdbcType=JdbcType.INTEGER)
    })
    String selectByName(String filename);
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zip
     *
     * @mbg.generated Sat Apr 13 12:01:15 CST 2019
     */
    @UpdateProvider(type=ZipSqlProvider.class, method="updateByExampleSelective")
    int updateByExampleSelective(@Param("record") Zip record, @Param("example") ZipExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zip
     *
     * @mbg.generated Sat Apr 13 12:01:15 CST 2019
     */
    @UpdateProvider(type=ZipSqlProvider.class, method="updateByExample")
    int updateByExample(@Param("record") Zip record, @Param("example") ZipExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zip
     *
     * @mbg.generated Sat Apr 13 12:01:15 CST 2019
     */
    @UpdateProvider(type=ZipSqlProvider.class, method="updateByPrimaryKeySelective")
    int updateByPrimaryKeySelective(Zip record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zip
     *
     * @mbg.generated Sat Apr 13 12:01:15 CST 2019
     */
    @Update({
        "update zip",
        "set taskid = #{taskid,jdbcType=INTEGER}",
        "where filename = #{filename,jdbcType=VARCHAR}"
    })
    int updateByPrimaryKey(Zip record);
}