package com.wzp.aiplatform.mapper;

import com.wzp.aiplatform.model.Zip;
import com.wzp.aiplatform.model.ZipExample;
import java.util.List;

import org.apache.ibatis.annotations.*;
import org.apache.ibatis.type.JdbcType;
import org.springframework.stereotype.Repository;

@Repository
public interface ZipMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zip
     *
     * @mbg.generated Fri Apr 12 17:38:29 CST 2019
     */
    @SelectProvider(type=ZipSqlProvider.class, method="countByExample")
    long countByExample(ZipExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zip
     *
     * @mbg.generated Fri Apr 12 17:38:29 CST 2019
     */
    @DeleteProvider(type=ZipSqlProvider.class, method="deleteByExample")
    int deleteByExample(ZipExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zip
     *
     * @mbg.generated Fri Apr 12 17:38:29 CST 2019
     */
    @Delete({
        "delete from zip",
        "where filename = #{filename,jdbcType=VARCHAR}"
    })
    int deleteByPrimaryKey(String filename);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zip
     *
     * @mbg.generated Fri Apr 12 17:38:29 CST 2019
     */
    @Insert({
        "insert into zip (filename)",
        "values (#{filename,jdbcType=VARCHAR})"
    })
    int insert(Zip record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zip
     *
     * @mbg.generated Fri Apr 12 17:38:29 CST 2019
     */
    @InsertProvider(type=ZipSqlProvider.class, method="insertSelective")
    int insertSelective(Zip record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zip
     *
     * @mbg.generated Fri Apr 12 17:38:29 CST 2019
     */
    @SelectProvider(type=ZipSqlProvider.class, method="selectByExample")
    @Results({
        @Result(column="filename", property="filename", jdbcType=JdbcType.VARCHAR, id=true)
    })
    List<Zip> selectByExample(ZipExample example);

    @Select({
            "select",
            "filename",
            "from zip",
            "where filename = #{filename,jdbcType=INTEGER}"
    })
    @Results({

            @Result(column="filename", property="filename", jdbcType=JdbcType.VARCHAR)
    })
    String selectByPrimaryKey(String filename);
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zip
     *
     * @mbg.generated Fri Apr 12 17:38:29 CST 2019
     */
    @UpdateProvider(type=ZipSqlProvider.class, method="updateByExampleSelective")
    int updateByExampleSelective(@Param("record") Zip record, @Param("example") ZipExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zip
     *
     * @mbg.generated Fri Apr 12 17:38:29 CST 2019
     */
    @UpdateProvider(type=ZipSqlProvider.class, method="updateByExample")
    int updateByExample(@Param("record") Zip record, @Param("example") ZipExample example);
}